image: alpine/edge
packages:
  - go
  # Required by codecov
  - bash
  - findutils
sources:
  - https://github.com/emersion/go-dkim
tasks:
  - build: |
      cd go-dkim
      go build -v
  - test: |
      cd go-dkim
      go test -coverprofile=coverage.txt -covermode=atomic
  - upload-coverage: |
      cd go-dkim
      export CODECOV_TOKEN=9110525a-8379-493f-9a4b-a14294ecd306
      curl -s https://codecov.io/bash | bash
